<?php
$this->headTitle('Reset Password');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Email address'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-large btn-primary'
]);

$form->prepare();
?>
<div class="cat__pages__login--fullscreen" style="background-image: url(img/login/1.jpg)">
    <div class="cat__pages__login__header">
        <div class="row">
            <div class="col-lg-8">
                <div class="cat__pages__login__header__logo">
                    <a href="javascript: history.back();">
                        <img src="img/logo-inverse.png" alt="Clean UI Admin Template" />
                    </a>
                    <a href="javascript: void(0);" class="btn btn-sm btn-outline ml-3 switch-to-fullscreen">Switch Fullscreen / Windowed</a>
                    <a href="javascript: void(0);" class="btn btn-sm btn-outline ml-3 random-bg-image" data-img="1">Randomize Background Image</a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cat__pages__login__header__menu">
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item"><a href="javascript: history.back();">&larr; Back</a></li>
                        <li class="list-inline-item active"><a href="javascript: void(0);">Login</a></li>
                        <li class="list-inline-item"><a href="javascript: void(0);">About</a></li>
                        <li class="list-inline-item"><a href="javascript: void(0);">Support</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="cat__pages__login__block">
        <div class="row">
            <div class="col-xl-12">
                <div class="cat__pages__login__block__promo text-white text-center">
                    <h1 class="mb-3">
                        <strong>WELCOME TO CLEAN UI ADMIN TEMPLATE</strong>
                    </h1>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been
                        the industry's standard dummy text ever since the 1500s.</p>
                </div>
                <div class="cat__pages__login__block__inner">
                    <div class="cat__pages__login__block__form">
                        <h4 class="text-uppercase">
                            <strong>Reset Password</strong>
                        </h4>
                        <br />
                        <?= $this->form()->openTag($form); ?>
                        <p>Enter your e-mail address below to reset your password</p>

                        <?= $this->formElement($form->get('email')); ?>
                        <?= $this->formElementErrors($form->get('email')); ?>                              

                        <?= $this->formElement($form->get('captcha')); ?>
                        <p class="hint">Enter the letters above as you see them.</p>

                        <?= $this->formElement($form->get('submit')); ?>

                        <?= $this->formElement($form->get('csrf')); ?>

                        <?= $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="cat__pages__login__footer text-center">
        <ul class="list-unstyled list-inline">
            <li class="list-inline-item"><a href="javascript: void(0);">Terms of Use</a></li>
            <li class="active list-inline-item"><a href="javascript: void(0);">Compliance</a></li>
            <li class="list-inline-item"><a href="javascript: void(0);">Confidential Information</a></li>
            <li class="list-inline-item"><a href="javascript: void(0);">Support</a></li>
            <li class="list-inline-item"><a href="javascript: void(0);">Contacts</a></li>
        </ul>
    </div>
</div>