<?php
$this->headTitle('Sign in');

$this->mainMenu()->setActiveItemId('login');

$form->get('username')->setAttributes([
            'class' => 'form-control',
            'placeholder' => 'Username',
            'required' => true,
            'autofocus' => true
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);

$form->get('password')->setAttributes([
            'id' => 'validation-password',
            'name' => 'validation[password]',
            'data-validation' => '[L>=6]',
            'data-validation-message' => '$ must be at least 6 characters',
            'class' => 'form-control password',
            'placeholder' => 'Password',
            'required' => true,
        ])
        ->setLabelAttributes([
            'class' => 'sr-only'
        ]);
?>
<!-- START: pages/login-alpha -->
<div class="cat__pages__login--fullscreen" style="background-image: url(img/login/1.jpg)">
    <div class="cat__pages__login__block">
        <div class="row">
            <div class="col-xl-12">
                <div class="cat__pages__login__block__promo text-white text-center">
                    <h1 class="mb-3">
                        <strong></strong>
                    </h1>
                    <p></p>
                </div>
                <div class="cat__pages__login__block__inner">
                    <div class="cat__pages__login__block__form">
                        <h4 class="text-uppercase">
                            <strong>Please log in</strong>
                        </h4>
                        <br />
                        <form id="form-validation" name="form-validation" class="form-signin" method="post">            
                            <div class="form-group">
                                <?= $this->formLabel($form->get('username')); ?>
                                <?= $this->formElement($form->get('username')); ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('password')); ?>
                                <?= $this->formElement($form->get('password')); ?>  
                            </div>
                            <div class="form-group">
                                <a href="<?= $this->url('reset-password') ?>" class="pull-right cat__core__link--blue cat__core__link--underlined">Forgot Password?</a>
                                <div class="checkbox chkbox_intl">
                                    <label>
                                        <?= $this->formElement($form->get('remember_me')); ?>
                                        Remember me
                                    </label>
                                </div>
                                <?= $this->formElement($form->get('redirect_url')); ?>
                                <?= $this->formElement($form->get('csrf')) ?> 
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary mr-3">Sign In</button>
                                <span class="register-link">
                                    <a href="" class="cat__core__link--blue cat__core__link--underlined">Register</a> if you don't have account
                                </span>
                            </div>
                            <div class="form-group">
                                <span>
                                    Use another service to Log In
                                </span>
                                <div class="mt-2">
                                    <a href="javascript: void(0);" class="btn btn-icon">
                                        <i class="icmn-facebook"></i>
                                    </a>
                                    <a href="javascript: void(0);" class="btn btn-icon">
                                        <i class="icmn-google"></i>
                                    </a>
                                    <a href="javascript: void(0);" class="btn btn-icon">
                                        <i class="icmn-windows"></i>
                                    </a>
                                    <a href="javascript: void(0);" class="btn btn-icon">
                                        <i class="icmn-twitter"></i>
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {

        $("#form-validation").validate({
            submit: {
                settings: {
                    inputContainer: '.form-group',
                    errorListClass: 'form-control-error',
                    errorClass: 'has-danger'
                }
            }
        });

        // Show/Hide Password
        $('.password').password({
            eyeClass: '',
            eyeOpenClass: 'icmn-eye',
            eyeCloseClass: 'icmn-eye-blocked'
        });

    });

</script>
<!-- END: pages/login-alpha -->
